In [1]:
import pandas as pd

In [4]:
fpath = "/nfs/turbo/umms-indikar/shared/projects/poreC/data/nagano2017/GSE94489/GSE94489_2i_diploids_features_table.txt.gz"

df = pd.read_csv(fpath, sep='\t')
df.head()

,batch_id,batch_name,cond,cell_nm,f_no_digestion,mean_f_fend_dup,max_chrom_cov_abber,f_trans,trans_align,total_contacts,...,passed_qc,mean_insu,loop_enr_EE,loop_enr_LL,ord,group,f_mitotic_band,f_near_band,far_mu,repli_score
0,11,1CDU_2312,1CDU,1CDU_1,0.234231,0.024752,0.278872,0.113668,0.234231,83348,...,1,2.580145,0.415037,0.397335,846.0,early-S,0.124002,0.699160,26099026.25,1.210399
1,11,1CDU_2312,1CDU,1CDU_2,0.216173,0.017595,0.378858,0.094847,0.204004,214629,...,1,2.551423,0.546692,0.621488,501.0,early-S,0.132541,0.671156,30249812.50,1.034900
2,11,1CDU_2312,1CDU,1CDU_4,0.190065,0.015667,0.440535,0.098173,0.221388,134191,...,1,2.590607,0.046543,1.257388,863.0,early-S,0.119652,0.708153,29919000.08,1.201354
3,11,1CDU_2312,1CDU,1CDU_5,0.275768,0.019523,0.479997,0.079888,0.218922,59471,...,1,2.503729,1.548437,1.295456,278.0,G1,0.151459,0.607182,26405727.93,1.122329
4,11,1CDU_2312,1CDU,1CDU_7,0.237210,0.020137,0.344837,0.083726,0.220891,130234,...,1,2.204179,0.882762,0.804276,1484.0,late-S/G2,0.090756,0.805974,25623027.85,1.228757

In [9]:
df['cell_nm'].nunique()

2924